/**
 * Forecast type definitions
 * Represents a multi-step prediction generated by a Prophet over a fixed time horizon
 */

// Fixed forecast horizons (in days) as per system design
export const FORECAST_HORIZONS = [5, 20, 60, 120, 240, 480, 1200, 2400] as const;
export type ForecastHorizon = typeof FORECAST_HORIZONS[number];

export interface Forecast {
  forecastId: string;  // {prophetId}_{horizon}d_{startDate}
  prophetId: string;
  assetId: string;
  
  // Time window
  horizon: ForecastHorizon;  // CHANGED: Now restricted to fixed windows
  startDate: string;  // YYYY-MM-DD - first prediction date
  endDate: string;    // YYYY-MM-DD - last prediction date (startDate + horizon days)
  
  // Multi-step predictions
  predictions: ForecastPrediction[];  // Length should equal horizon
  
  // Performance metrics (if actual data available for comparison)
  performance?: {
    rmse?: number;
    mape?: number;
    r2?: number;
    directionalAccuracy?: number;
    
    // Per-window performance breakdown
    windows?: {
      '5d'?: PerformanceMetrics;
      '20d'?: PerformanceMetrics;
      '60d'?: PerformanceMetrics;
      '120d'?: PerformanceMetrics;
      '240d'?: PerformanceMetrics;
      '480d'?: PerformanceMetrics;
      '1200d'?: PerformanceMetrics;
      '2400d'?: PerformanceMetrics;
    };
  };
  
  status: 'generating' | 'complete' | 'failed';
  createdAt: string;
}

export interface ForecastPrediction {
  date: string;      // YYYY-MM-DD
  predictedValue: number;     // Predicted value
  actualValue?: number;       // Actual value (if known)
  confidence?: {
    lower: number;
    upper: number;
  };
}

interface PerformanceMetrics {
  rmse: number;
  mape: number;
  r2: number;
  directionalAccuracy: number;
}

export interface CreateForecastInput {
  forecastId: string;
  prophetId: string;
  assetId: string;
  horizon: ForecastHorizon;  // CHANGED: Now typed to fixed horizons
  startDate: string;
  endDate: string;
  predictions: ForecastPrediction[];
}
